### ISSUE TITLE
x86_64 target machinize start_sp_from_bp_offset

### ISSUE THREAD

**Issue by logzero** [vnmakarov/mir#68] opened 2020-03-31 21:34 UTC
I think I am hitting a bug with the hard coded start_sp_from_bp_offset=8 in target_machinize.

You can have a function that won't generate a prologue/epilogue, doesn't touch stack, but has args passed on the stack. start_sp_from_bp_offset shold be 0 in that case right?

My test function is (e will be passed on stack on WIN64):
int foo(int a, float b, int c, float d, int e) { return a+c+e; }

**Comment by logzero** [comment] 2020-04-01 18:05
A portable example function:

int square(int a, int b, int c, int d, int e, int f, int g) {return g;}

ret_type = MIR_T_I32;
func = MIR_new_func (ctx, "test", 1, &ret_type, 7,  MIR_T_I32, "a", MIR_T_I32, "b", MIR_T_I32, "c", MIR_T_I32, "d", MIR_T_I32, "e", MIR_T_I32, "f", MIR_T_I32, "g");
MIR_reg_t g = MIR_reg (ctx, "g", func->u.func);
MIR_reg_t r = MIR_new_func_reg (ctx, func->u.func, MIR_T_I64, "r");
MIR_append_insn (ctx, func, MIR_new_insn (ctx, MIR_MOV, MIR_new_reg_op (ctx, r), MIR_new_reg_op (ctx, g)));
MIR_append_insn (ctx, func, MIR_new_ret_insn (ctx, 1, MIR_new_reg_op (ctx, r)));

Actually the issue is even worse as the ptr used for stack arg access is rbp:
mov    0x10(%rbp),%rax
movslq %eax,%rax
movslq %eax,%rax
retq

A simple fix would be to set bp whenever func has stack args I guess. Although its extra needless instructions.

**Comment by vnmakarov** [comment] 2020-04-01 21:13
Thank you for reporting this bug.

Yes, the problem is even worse.  I'll fix it tomorrow.

**Comment by vnmakarov** [comment] 2020-04-02 02:31
I've fixed and the fix is in the repository.

**Comment by kalvdans** [comment] 2020-04-02 16:11
Thanks, for completeness I will link the commits here:
Fix: https://github.com/vnmakarov/mir/commit/bfa5da4b9b1c2f2b2053e1ec46def8ceafe1aa1f
Test: https://github.com/vnmakarov/mir/commit/254bfcd8c12fa268249f06e171a74c6b22094106

**Closed** 2020-04-03 21:17 UTC
