### ISSUE TITLE
Failure with MIR_gen_set_optimize_level on Apple M1

### ISSUE THREAD

**Issue by sletz** [vnmakarov/mir#182] opened 2021-07-13 16:27 UTC
We get this error when compiling some DSP programs using `MIR_gen_set_optimize_level` with level 0 in our [Faust => MIR backend](https://github.com/grame-cncm/faust/blob/master-dev/compiler/generator/interpreter/fbc_mir_compiler.hh): 

`fatal failure in matching insn:	mov	i64:97552(hr29), hr19`

Note that:
- this error does not occur with optimisation level from 1 to 3
- this error does not occur with the same DSP program and X86_64 code generation

**Comment by vnmakarov** [comment] 2021-07-14 17:23
Thank you for reporting this.

Could you send me mir textual file which generates this error.

I suspect the problem is the offset of the store.  Probably it is out of possible range.  It can happen for -O0 as MIR generator does not reuse stack slots in this mode.  This problem was even worse for older -O0 mode implementation.  Therefore I changed it.  Still I see the bug occurs.

So I need to fix it somehow and your test could help me a lot.

**Comment by sletz** [comment] 2021-07-14 17:44
Here is the file produced after adding `MIR_output(fContext, stdout);` at line 1082
https://github.com/grame-cncm/faust/blob/master-dev/compiler/generator/interpreter/fbc_mir_compiler.hh#L1082
[STunedBar6.txt](https://github.com/vnmakarov/mir/files/6818017/STunedBar6.txt)

**Comment by vnmakarov** [comment] 2021-07-15 18:23
Thank you for the test.  After some its modification I reproduced the bug.

I think the fix will be ready on this week.

**Comment by vnmakarov** [comment] 2021-07-16 13:40
I add new insn patterns which should permit longer displacements:

https://github.com/vnmakarov/mir/commit/6148f44838b10a79084933d86cdfc07853ca07c0

There is no failure of matching on your test anymore.
Thank your for reporting this.

**Comment by sletz** [comment] 2021-07-16 14:14
Hum.. now it crash at runtime ! (and working with other optimisation levels). Here is the level = 0  generated MIR code:
[STunedBar6.txt](https://github.com/vnmakarov/mir/files/6831238/STunedBar6.txt)

**Comment by vnmakarov** [comment] 2021-07-16 15:13
OK.  The generated MIR code should be the same.  The generated machine code should be different.

To reproduce the bug now I should see the generated machine code.  It means I need all the program (including main function) or if there is not main function I need all the data passed as arguments to func `compute`.

Could you provide all I need to run function `compute`.  It would greatly help me in fixing the bug.
Thank you.

**Comment by sletz** [comment] 2021-07-16 16:37
Now easy to install and run the complete chain. Is there as simple way to generate the machine code that could be sent?

**Comment by vnmakarov** [comment] 2021-07-17 22:08
I understand.  Something should be added to MIR simplify this problem.  I'll think about it.

Meanwhile, I'll try to fix the bug by myself.  I think I can simulate the new insn pattern usage w/o big MIR code.  It could be done by switching off patterns used for small (12-bit) memory displacement.  I'll write about the progress on the next week.

**Comment by vnmakarov** [comment] 2021-07-19 19:04
I reverted the previous changes and committed a patch implementing another approach to deal with long memory displacements:

https://github.com/vnmakarov/mir/commit/e740fc5cacaf69d12772385e53b664fdd8e7a622

Could you, please, check that the new changes solves the bug.

**Comment by sletz** [comment] 2021-07-19 19:53
Yes, working now, thanks.

**Closed** 2021-07-20 21:31 UTC
